// apps/web/src/views/BackgroundRemoveView.vue
<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import AiCostConfirmDialog from '@/features/ai-shared/AiCostConfirmDialog.vue'
import { useRuntimeConfigStore } from '@/stores/runtimeConfig'
import { useAppearanceStore } from '@/stores/appearance'
import { useAuthStore } from '@/stores/auth'
import { useClientWalletBalance } from '@/composables/useClientWalletBalance'
import { removeImageBackground, uploadAiInputFile } from '@/services/aiWallpaper'
import { downloadAuthenticatedMedia } from '@/services/authenticatedMedia'
import { formatPoints } from '@/services/billingApi'
import notificationService from '@/services/notification'

const STAGE_META = {
  idle: { label: '等待上传', detail: '选择一张图片开始抠图' },
  ready: { label: '准备就绪', detail: '点击下方按钮移除背景' },
  uploading: { label: '上传原图', detail: '正在安全上传到处理通道' },
  queued: { label: '排队中', detail: '任务已创建，等待算力分配' },
  running: { label: '智能抠图', detail: '正在分离主体与背景' },
  succeeded: { label: '处理完成', detail: '透明 PNG 已就绪，可下载' },
  failed: { label: '处理失败', detail: '可更换图片或重试' },
}

const STAGE_ORDER = ['uploading', 'queued', 'running', 'succeeded']

const runtimeConfigStore = useRuntimeConfigStore()
const appearanceStore = useAppearanceStore()
const authStore = useAuthStore()
const { availableCents, refreshWalletBalance } = useClientWalletBalance()
const fileInput = ref(null)
const sourceFile = ref(null)
const sourcePreview = ref('')
const resultUrl = ref('')
const processing = ref(false)
const dragging = ref(false)
const costConfirmOpen = ref(false)
const pendingCost = ref(null)
const stage = ref('idle')
const errorMessage = ref('')
const resultReveal = ref(false)

const toolModels = computed(() => {
  const models = runtimeConfigStore.getFeaturePayload('ai.imageTools')?.backgroundRemovalModels
  return Array.isArray(models) ? models.filter((model) => model?.id) : []
})
const activeTool = computed(
  () => toolModels.value.find((model) => model.default === true) || toolModels.value[0] || null,
)
const unitPrice = computed(() => Math.max(0, Number(activeTool.value?.pricePoints || 0)))
const canRun = computed(() => Boolean(sourceFile.value && activeTool.value && !processing.value))
const stageMeta = computed(() => STAGE_META[stage.value] || STAGE_META.idle)
const stageIndex = computed(() => {
  if (stage.value === 'failed') return 1
  if (stage.value === 'ready' || stage.value === 'idle') return -1
  return STAGE_ORDER.indexOf(stage.value)
})
const statusTone = computed(() => {
  if (stage.value === 'failed') return 'danger'
  if (stage.value === 'succeeded') return 'success'
  if (processing.value) return 'busy'
  if (sourceFile.value) return 'ready'
  return 'idle'
})

function releaseSourcePreview() {
  if (sourcePreview.value.startsWith('blob:')) URL.revokeObjectURL(sourcePreview.value)
  sourcePreview.value = ''
}

function selectFile(file) {
  if (!file || processing.value) return
  if (!String(file.type || '').startsWith('image/')) {
    notificationService.warning('请选择 PNG、JPG 或 WebP 图片')
    return
  }
  if (file.size > 15 * 1024 * 1024) {
    notificationService.warning('图片不能超过 15MB')
    return
  }
  releaseSourcePreview()
  sourceFile.value = file
  sourcePreview.value = URL.createObjectURL(file)
  resultUrl.value = ''
  resultReveal.value = false
  errorMessage.value = ''
  stage.value = 'ready'
}

function handleFileChange(event) {
  selectFile(event.target.files?.[0])
  event.target.value = ''
}

function handleDrop(event) {
  dragging.value = false
  selectFile(event.dataTransfer?.files?.[0])
}

function clearImage() {
  if (processing.value) return
  releaseSourcePreview()
  sourceFile.value = null
  resultUrl.value = ''
  resultReveal.value = false
  errorMessage.value = ''
  stage.value = 'idle'
}

function applyTaskStage(task) {
  const status = String(task?.status || '')
    .trim()
    .toLowerCase()
  if (status === 'queued') stage.value = 'queued'
  else if (status === 'running') stage.value = 'running'
  else if (status === 'succeeded') stage.value = 'succeeded'
  else if (status === 'failed' || status === 'canceled') stage.value = 'failed'
}

async function executeBackgroundRemoval() {
  if (!canRun.value) return
  costConfirmOpen.value = false
  pendingCost.value = null
  processing.value = true
  resultUrl.value = ''
  resultReveal.value = false
  errorMessage.value = ''
  stage.value = 'uploading'
  try {
    const uploadedUrl = await uploadAiInputFile(sourceFile.value)
    stage.value = 'queued'
    const response = await removeImageBackground(uploadedUrl, activeTool.value.id, {
      onUpdate: applyTaskStage,
    })
    const output = response?.result?.outputs?.[0] || response?.job?.originalMediaUrls?.[0] || ''
    if (!output) throw new Error('任务已完成，但没有返回图片')
    resultUrl.value = output
    stage.value = 'succeeded'
    requestAnimationFrame(() => {
      resultReveal.value = true
    })
    notificationService.success('背景已移除')
  } catch (error) {
    stage.value = 'failed'
    errorMessage.value = error?.message || '背景移除失败'
    notificationService.error(errorMessage.value)
  } finally {
    processing.value = false
    void refreshWalletBalance({ force: true })
  }
}

async function requestBackgroundRemoval() {
  if (!canRun.value) return
  if (authStore.user?.requireCostConfirm === false) {
    await executeBackgroundRemoval()
    return
  }
  await refreshWalletBalance({ force: true }).catch(() => null)
  pendingCost.value = {
    billingMode: 'credits',
    unitCost: unitPrice.value,
    unitPriceCents: unitPrice.value,
    totalPriceCents: unitPrice.value,
    count: 1,
    creditAvailable: availableCents.value,
    featureLabel: '背景移除',
  }
  costConfirmOpen.value = true
}

function cancelCostConfirm() {
  costConfirmOpen.value = false
  pendingCost.value = null
}

async function downloadResult() {
  if (!resultUrl.value) return
  try {
    await downloadAuthenticatedMedia(resultUrl.value, `background-removed-${Date.now()}.png`)
    notificationService.success('已开始下载')
  } catch (error) {
    notificationService.error(error?.message || '下载失败')
  }
}

onMounted(async () => {
  await runtimeConfigStore.loadRuntimeConfig({ force: true }).catch(() => null)
})

onBeforeUnmount(releaseSourcePreview)
</script>

<template>
  <main
    class="br"
    :class="{
      'is-dark': appearanceStore.isDark,
      'is-processing': processing,
      'is-done': stage === 'succeeded',
      'is-failed': stage === 'failed',
    }"
  >
    <div class="br-glow" aria-hidden="true"></div>

    <header class="br-header">
      <div class="br-header__copy">
        <span class="br-kicker">
          <i class="bi bi-scissors" aria-hidden="true"></i>
          图片工具
        </span>
        <h1>背景移除</h1>
        <p>上传商品或人像图，一键保留主体并导出透明 PNG，可直接用于电商主图与合成。</p>
        <div class="br-meta">
          <span class="br-chip">
            <i class="bi bi-filetype-png" aria-hidden="true"></i>
            透明 PNG
          </span>
          <span class="br-chip">
            <i class="bi bi-image" aria-hidden="true"></i>
            最大 15MB
          </span>
          <span v-if="activeTool" class="br-chip is-price">
            <i class="bi bi-coin" aria-hidden="true"></i>
            {{ formatPoints(unitPrice) }} / 张
          </span>
          <span v-else class="br-chip is-warn">工具未开放</span>
        </div>
      </div>

      <aside class="br-status" :data-tone="statusTone" aria-live="polite">
        <div class="br-status__pulse" aria-hidden="true"></div>
        <div class="br-status__copy">
          <small>当前状态</small>
          <strong>{{ stageMeta.label }}</strong>
          <p>{{ errorMessage || stageMeta.detail }}</p>
        </div>
        <ol class="br-steps" aria-label="处理进度">
          <li
            v-for="(key, index) in STAGE_ORDER"
            :key="key"
            :class="{
              'is-done': stageIndex > index || (stage === 'succeeded' && index === STAGE_ORDER.length - 1),
              'is-active': stageIndex === index,
            }"
          >
            <span>{{ STAGE_META[key].label }}</span>
          </li>
        </ol>
      </aside>
    </header>

    <section class="br-workspace" aria-label="背景移除工作区">
      <div
        class="br-pane"
        :class="{ 'is-dragging': dragging, 'has-image': Boolean(sourcePreview) }"
        @dragenter.prevent="dragging = true"
        @dragover.prevent="dragging = true"
        @dragleave.prevent="dragging = false"
        @drop.prevent="handleDrop"
      >
        <div class="br-pane__head">
          <strong>原图</strong>
          <span v-if="sourceFile">{{ sourceFile.name }}</span>
          <button
            v-if="sourceFile"
            type="button"
            class="br-ghost"
            :disabled="processing"
            @click="clearImage"
          >
            <i class="bi bi-trash3" aria-hidden="true"></i>
            清空
          </button>
        </div>

        <button
          v-if="!sourcePreview"
          type="button"
          class="br-dropzone"
          @click="fileInput?.click()"
        >
          <span class="br-dropzone__icon" aria-hidden="true">
            <i class="bi bi-cloud-arrow-up"></i>
          </span>
          <strong>上传图片</strong>
          <span>点击选择，或拖入 PNG / JPG / WebP</span>
        </button>

        <div v-else class="br-frame">
          <img :src="sourcePreview" alt="待处理原图" />
          <div v-if="processing" class="br-scan" aria-hidden="true">
            <span class="br-scan__beam"></span>
            <span class="br-scan__veil"></span>
          </div>
          <button type="button" class="br-frame__action" :disabled="processing" @click="fileInput?.click()">
            <i class="bi bi-arrow-repeat" aria-hidden="true"></i>
            更换
          </button>
        </div>
      </div>

      <div class="br-bridge" aria-hidden="true">
        <div class="br-bridge__rail">
          <span v-for="n in 5" :key="n" class="br-bridge__dot"></span>
        </div>
        <div class="br-bridge__orb">
          <i class="bi" :class="processing ? 'bi-hourglass-split' : resultUrl ? 'bi-check-lg' : 'bi-scissors'"></i>
        </div>
      </div>

      <div class="br-pane is-result" :class="{ 'has-result': Boolean(resultUrl) }">
        <div class="br-pane__head">
          <strong>透明结果</strong>
          <span v-if="resultUrl">PNG · 透明通道</span>
          <span v-else-if="processing">处理中</span>
        </div>

        <div v-if="resultUrl" class="br-frame is-checker" :class="{ 'is-reveal': resultReveal }">
          <img :src="resultUrl" alt="背景移除结果" />
          <div class="br-frame__badge">
            <i class="bi bi-check2-circle" aria-hidden="true"></i>
            已抠图
          </div>
        </div>

        <div v-else class="br-empty" :class="{ 'is-busy': processing }">
          <div class="br-loader" aria-hidden="true">
            <span class="br-loader__ring"></span>
            <span class="br-loader__ring is-delay"></span>
            <span class="br-loader__core">
              <i class="bi" :class="processing ? 'bi-magic' : 'bi-person-bounding-box'"></i>
            </span>
          </div>
          <strong>{{ processing ? stageMeta.label : '结果将在这里显示' }}</strong>
          <p>{{ processing ? stageMeta.detail : '移除背景后可预览透明底与下载 PNG' }}</p>
          <div v-if="processing" class="br-progress" aria-hidden="true">
            <span></span>
          </div>
        </div>
      </div>
    </section>

    <footer class="br-actions">
      <div class="br-actions__hint">
        <template v-if="!activeTool">后台尚未开放背景移除工具</template>
        <template v-else-if="processing">请保持页面打开，完成后可立即下载</template>
        <template v-else-if="resultUrl">结果已生成，可继续更换图片再抠一张</template>
        <template v-else>上传后按张扣积分；失败或取消会自动返还</template>
      </div>
      <div class="br-actions__btns">
        <button
          type="button"
          class="br-btn is-primary"
          :disabled="!canRun"
          @click="requestBackgroundRemoval"
        >
          <i
            class="bi"
            :class="processing ? 'bi-arrow-repeat br-spin' : 'bi-magic'"
            aria-hidden="true"
          ></i>
          {{ processing ? '处理中…' : stage === 'failed' ? '重新移除背景' : '移除背景' }}
        </button>
        <button
          type="button"
          class="br-btn is-secondary"
          :disabled="!resultUrl"
          @click="downloadResult"
        >
          <i class="bi bi-download" aria-hidden="true"></i>
          下载 PNG
        </button>
      </div>
    </footer>

    <input
      ref="fileInput"
      type="file"
      accept="image/png,image/jpeg,image/webp"
      hidden
      @change="handleFileChange"
    />

    <AiCostConfirmDialog
      :show="costConfirmOpen"
      :cost="pendingCost"
      :light="!appearanceStore.isDark"
      @confirm="executeBackgroundRemoval"
      @cancel="cancelCostConfirm"
    />
  </main>
</template>

<style scoped>
.br {
  --br-ink: #14201f;
  --br-muted: #5f726e;
  --br-line: #d7e4e0;
  --br-bg: #f3f7f6;
  --br-surface: #ffffff;
  --br-soft: #e8f3f0;
  --br-accent: #0f9d8a;
  --br-accent-2: #14b8a6;
  --br-accent-soft: rgb(15 157 138 / 12%);
  --br-danger: #e11d48;
  --br-success: #059669;
  --br-frame: #e6eeeb;
  --br-shadow: 0 18px 48px rgb(20 50 45 / 8%);
  position: relative;
  isolation: isolate;
  min-height: calc(100dvh - var(--app-header-offset, 72px));
  padding: 28px clamp(20px, 3.5vw, 56px) 36px;
  overflow: clip;
  color: var(--br-ink);
  background: var(--br-bg);
}

.br.is-dark {
  --br-ink: #eef7f4;
  --br-muted: #9bb0aa;
  --br-line: #2a3633;
  --br-bg: #0e1211;
  --br-surface: #171c1b;
  --br-soft: #1c2623;
  --br-accent: #2dd4bf;
  --br-accent-2: #5eead4;
  --br-accent-soft: rgb(45 212 191 / 14%);
  --br-danger: #fb7185;
  --br-success: #34d399;
  --br-frame: #121716;
  --br-shadow: 0 22px 52px rgb(0 0 0 / 35%);
}

.br-glow {
  position: absolute;
  inset: 0;
  z-index: -1;
  pointer-events: none;
  background:
    radial-gradient(circle at 12% 0%, rgb(20 184 166 / 16%), transparent 28%),
    radial-gradient(circle at 88% 8%, rgb(56 189 248 / 10%), transparent 24%),
    linear-gradient(180deg, color-mix(in srgb, var(--br-soft) 70%, transparent), transparent 42%);
}

.br-header {
  display: grid;
  grid-template-columns: minmax(0, 1.4fr) minmax(280px, 0.85fr);
  gap: 20px;
  max-width: 1280px;
  margin: 0 auto 22px;
  align-items: stretch;
}

.br-header__copy {
  display: grid;
  align-content: center;
  gap: 10px;
  padding: 8px 4px;
}

.br-kicker {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  width: fit-content;
  color: var(--br-accent);
  font-size: 0.74rem;
  font-weight: 800;
  letter-spacing: 0.12em;
}

.br-header h1 {
  margin: 0;
  font-size: clamp(2rem, 3.6vw, 2.75rem);
  font-weight: 900;
  letter-spacing: -0.04em;
  line-height: 1.05;
}

.br-header__copy > p {
  margin: 0;
  max-width: 48ch;
  color: var(--br-muted);
  font-size: 0.98rem;
  line-height: 1.65;
}

.br-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 4px;
}

.br-chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  min-height: 30px;
  padding: 0 11px;
  border: 1px solid var(--br-line);
  border-radius: 999px;
  background: color-mix(in srgb, var(--br-surface) 80%, transparent);
  color: var(--br-muted);
  font-size: 0.74rem;
  font-weight: 700;
}

.br-chip.is-price {
  color: var(--br-accent);
  border-color: color-mix(in srgb, var(--br-accent) 35%, var(--br-line));
  background: var(--br-accent-soft);
}

.br-chip.is-warn {
  color: var(--br-danger);
  border-color: color-mix(in srgb, var(--br-danger) 35%, var(--br-line));
}

.br-status {
  position: relative;
  display: grid;
  gap: 14px;
  padding: 18px 18px 16px;
  overflow: hidden;
  border: 1px solid var(--br-line);
  border-radius: 20px;
  background: var(--br-surface);
  box-shadow: var(--br-shadow);
}

.br-status__pulse {
  position: absolute;
  top: 18px;
  right: 18px;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--br-muted);
  box-shadow: 0 0 0 0 color-mix(in srgb, var(--br-muted) 40%, transparent);
}

.br-status[data-tone='busy'] .br-status__pulse {
  background: var(--br-accent);
  animation: br-pulse 1.6s ease-out infinite;
}

.br-status[data-tone='success'] .br-status__pulse {
  background: var(--br-success);
}

.br-status[data-tone='danger'] .br-status__pulse {
  background: var(--br-danger);
}

.br-status[data-tone='ready'] .br-status__pulse {
  background: var(--br-accent-2);
}

.br-status__copy small {
  display: block;
  color: var(--br-muted);
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 0.08em;
}

.br-status__copy strong {
  display: block;
  margin-top: 4px;
  font-size: 1.15rem;
  font-weight: 850;
  letter-spacing: -0.02em;
}

.br-status__copy p {
  margin: 6px 0 0;
  color: var(--br-muted);
  font-size: 0.82rem;
  line-height: 1.45;
}

.br-steps {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 6px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.br-steps li {
  position: relative;
  display: grid;
  gap: 6px;
  min-width: 0;
  color: var(--br-muted);
  font-size: 0.66rem;
  font-weight: 700;
}

.br-steps li::before {
  content: '';
  display: block;
  height: 4px;
  border-radius: 999px;
  background: var(--br-line);
  transition:
    background 220ms ease,
    box-shadow 220ms ease;
}

.br-steps li.is-done::before,
.br-steps li.is-active::before {
  background: linear-gradient(90deg, var(--br-accent), var(--br-accent-2));
}

.br-steps li.is-active::before {
  box-shadow: 0 0 0 3px var(--br-accent-soft);
  animation: br-step-glow 1.4s ease-in-out infinite;
}

.br-steps li span {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.br-workspace {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 72px minmax(0, 1fr);
  gap: 0;
  align-items: stretch;
  max-width: 1280px;
  height: min(62vh, 680px);
  min-height: 460px;
  margin: 0 auto;
}

.br-pane {
  display: flex;
  min-width: 0;
  flex-direction: column;
  overflow: hidden;
  border: 1px solid var(--br-line);
  border-radius: 22px;
  background: var(--br-surface);
  box-shadow: var(--br-shadow);
  transition:
    border-color 180ms ease,
    box-shadow 180ms ease,
    transform 180ms ease;
}

.br-pane.is-dragging {
  border-color: var(--br-accent);
  box-shadow:
    0 0 0 3px var(--br-accent-soft),
    var(--br-shadow);
}

.br-pane__head {
  display: flex;
  flex: 0 0 auto;
  align-items: center;
  gap: 12px;
  min-height: 52px;
  padding: 0 16px 0 18px;
  border-bottom: 1px solid var(--br-line);
}

.br-pane__head strong {
  font-size: 0.9rem;
  font-weight: 800;
}

.br-pane__head span {
  min-width: 0;
  overflow: hidden;
  color: var(--br-muted);
  font-size: 0.72rem;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.br-pane__head .br-ghost {
  margin-left: auto;
}

.br-ghost,
.br-btn,
.br-frame__action {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 7px;
  border: 1px solid var(--br-line);
  border-radius: 12px;
  background: var(--br-surface);
  color: inherit;
  font: inherit;
  font-weight: 750;
  cursor: pointer;
}

.br-ghost {
  min-height: 32px;
  padding: 0 10px;
  color: var(--br-muted);
  font-size: 0.74rem;
}

.br-dropzone {
  display: grid;
  flex: 1;
  place-content: center;
  gap: 10px;
  padding: 24px;
  border: 0;
  background:
    linear-gradient(180deg, color-mix(in srgb, var(--br-soft) 70%, transparent), transparent),
    transparent;
  color: var(--br-muted);
  cursor: pointer;
}

.br-dropzone__icon {
  display: grid;
  width: 64px;
  height: 64px;
  place-items: center;
  margin: 0 auto 4px;
  border-radius: 20px;
  color: var(--br-accent);
  background: var(--br-accent-soft);
  font-size: 1.7rem;
  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--br-accent) 18%, transparent);
}

.br-dropzone strong {
  color: var(--br-ink);
  font-size: 1.05rem;
  font-weight: 850;
}

.br-dropzone span {
  font-size: 0.84rem;
}

.br-frame {
  position: relative;
  display: grid;
  flex: 1;
  min-height: 0;
  place-items: center;
  padding: 22px;
  overflow: hidden;
  background: var(--br-frame);
}

.br-frame.is-checker {
  background-color: #fff;
  background-image:
    linear-gradient(45deg, #dfe7e4 25%, transparent 25%),
    linear-gradient(-45deg, #dfe7e4 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, #dfe7e4 75%),
    linear-gradient(-45deg, transparent 75%, #dfe7e4 75%);
  background-position: 0 0, 0 12px, 12px -12px, -12px 0;
  background-size: 24px 24px;
}

.br.is-dark .br-frame.is-checker {
  background-color: #101413;
  background-image:
    linear-gradient(45deg, #1b2321 25%, transparent 25%),
    linear-gradient(-45deg, #1b2321 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, #1b2321 75%),
    linear-gradient(-45deg, transparent 75%, #1b2321 75%);
}

.br-frame img {
  width: 100%;
  height: 100%;
  object-fit: contain;
  transition:
    opacity 420ms ease,
    transform 520ms cubic-bezier(0.22, 1, 0.36, 1),
    filter 520ms ease;
}

.br-frame.is-checker img {
  opacity: 0;
  transform: translateY(10px) scale(0.98);
  filter: blur(4px);
}

.br-frame.is-checker.is-reveal img {
  opacity: 1;
  transform: none;
  filter: none;
}

.br-frame__action,
.br-frame__badge {
  position: absolute;
  z-index: 2;
}

.br-frame__action {
  right: 14px;
  bottom: 14px;
  min-height: 36px;
  padding: 0 12px;
  color: var(--br-ink);
  background: color-mix(in srgb, var(--br-surface) 92%, transparent);
  backdrop-filter: blur(10px);
  font-size: 0.78rem;
}

.br-frame__badge {
  top: 14px;
  left: 14px;
  display: inline-flex;
  align-items: center;
  gap: 6px;
  min-height: 30px;
  padding: 0 10px;
  border-radius: 999px;
  color: #fff;
  background: color-mix(in srgb, var(--br-success) 92%, #000);
  font-size: 0.72rem;
  font-weight: 800;
}

.br-scan {
  position: absolute;
  inset: 0;
  pointer-events: none;
  overflow: hidden;
}

.br-scan__veil {
  position: absolute;
  inset: 0;
  background: linear-gradient(180deg, rgb(15 157 138 / 8%), transparent 40%, rgb(15 157 138 / 10%));
}

.br-scan__beam {
  position: absolute;
  left: -8%;
  width: 116%;
  height: 18%;
  background: linear-gradient(
    180deg,
    transparent,
    rgb(45 212 191 / 28%),
    rgb(255 255 255 / 55%),
    rgb(45 212 191 / 28%),
    transparent
  );
  filter: blur(0.4px);
  animation: br-scan 1.8s ease-in-out infinite;
}

.br-bridge {
  position: relative;
  display: grid;
  place-items: center;
}

.br-bridge__rail {
  position: absolute;
  top: 50%;
  left: 12px;
  right: 12px;
  display: flex;
  justify-content: space-between;
  transform: translateY(-50%);
}

.br-bridge__dot {
  width: 5px;
  height: 5px;
  border-radius: 50%;
  background: var(--br-line);
}

.br.is-processing .br-bridge__dot {
  animation: br-flow 1.1s ease-in-out infinite;
}

.br.is-processing .br-bridge__dot:nth-child(2) {
  animation-delay: 0.12s;
}
.br.is-processing .br-bridge__dot:nth-child(3) {
  animation-delay: 0.24s;
}
.br.is-processing .br-bridge__dot:nth-child(4) {
  animation-delay: 0.36s;
}
.br.is-processing .br-bridge__dot:nth-child(5) {
  animation-delay: 0.48s;
}

.br-bridge__orb {
  position: relative;
  z-index: 1;
  display: grid;
  width: 46px;
  height: 46px;
  place-items: center;
  border: 1px solid color-mix(in srgb, var(--br-accent) 35%, var(--br-line));
  border-radius: 50%;
  color: var(--br-accent);
  background: var(--br-surface);
  box-shadow: var(--br-shadow);
  font-size: 1.15rem;
}

.br.is-processing .br-bridge__orb {
  animation: br-orb 1.4s ease-in-out infinite;
}

.br.is-done .br-bridge__orb {
  color: #fff;
  background: var(--br-success);
  border-color: transparent;
}

.br-empty {
  display: grid;
  flex: 1;
  place-content: center;
  justify-items: center;
  gap: 10px;
  padding: 28px 20px;
  text-align: center;
  background:
    linear-gradient(180deg, color-mix(in srgb, var(--br-soft) 55%, transparent), transparent 50%),
    var(--br-surface);
}

.br-empty strong {
  font-size: 1rem;
  font-weight: 850;
}

.br-empty p {
  margin: 0;
  max-width: 28ch;
  color: var(--br-muted);
  font-size: 0.82rem;
  line-height: 1.5;
}

.br-loader {
  position: relative;
  display: grid;
  width: 88px;
  height: 88px;
  place-items: center;
  margin-bottom: 6px;
}

.br-loader__ring {
  position: absolute;
  inset: 0;
  border: 2px solid transparent;
  border-top-color: var(--br-accent);
  border-right-color: color-mix(in srgb, var(--br-accent) 35%, transparent);
  border-radius: 50%;
  opacity: 0.35;
}

.br-empty.is-busy .br-loader__ring {
  opacity: 1;
  animation: br-spin 1.1s linear infinite;
}

.br-empty.is-busy .br-loader__ring.is-delay {
  inset: 10px;
  animation-direction: reverse;
  animation-duration: 1.6s;
  border-top-color: var(--br-accent-2);
}

.br-loader__core {
  display: grid;
  width: 52px;
  height: 52px;
  place-items: center;
  border-radius: 18px;
  color: var(--br-accent);
  background: var(--br-accent-soft);
  font-size: 1.35rem;
}

.br-empty.is-busy .br-loader__core {
  animation: br-breathe 1.5s ease-in-out infinite;
}

.br-progress {
  width: min(220px, 70%);
  height: 4px;
  overflow: hidden;
  margin-top: 6px;
  border-radius: 999px;
  background: var(--br-line);
}

.br-progress span {
  display: block;
  width: 42%;
  height: 100%;
  border-radius: inherit;
  background: linear-gradient(90deg, var(--br-accent), var(--br-accent-2));
  animation: br-progress 1.35s ease-in-out infinite;
}

.br-actions {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 14px;
  max-width: 1280px;
  margin: 18px auto 0;
}

.br-actions__hint {
  color: var(--br-muted);
  font-size: 0.82rem;
}

.br-actions__btns {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.br-btn {
  min-height: 44px;
  min-width: 138px;
  padding: 0 18px;
  font-size: 0.9rem;
  transition:
    transform 160ms ease,
    background 160ms ease,
    border-color 160ms ease,
    opacity 160ms ease;
}

.br-btn.is-primary {
  color: #fff;
  border-color: transparent;
  background: linear-gradient(135deg, var(--br-accent), var(--br-accent-2));
  box-shadow: 0 12px 28px rgb(15 157 138 / 24%);
}

.br-btn.is-secondary {
  color: var(--br-ink);
  background: var(--br-surface);
}

.br-btn:hover:not(:disabled) {
  transform: translateY(-1px);
}

.br-btn:disabled {
  cursor: not-allowed;
  opacity: 0.45;
  transform: none;
}

.br-spin {
  animation: br-spin 0.85s linear infinite;
}

@keyframes br-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes br-scan {
  0% {
    top: -20%;
  }
  100% {
    top: 110%;
  }
}

@keyframes br-pulse {
  0% {
    box-shadow: 0 0 0 0 color-mix(in srgb, var(--br-accent) 45%, transparent);
  }
  70% {
    box-shadow: 0 0 0 12px transparent;
  }
  100% {
    box-shadow: 0 0 0 0 transparent;
  }
}

@keyframes br-step-glow {
  50% {
    filter: brightness(1.15);
  }
}

@keyframes br-flow {
  0%,
  100% {
    background: var(--br-line);
    transform: scale(0.9);
  }
  50% {
    background: var(--br-accent);
    transform: scale(1.25);
  }
}

@keyframes br-orb {
  0%,
  100% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.06);
  }
}

@keyframes br-breathe {
  0%,
  100% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.05);
  }
}

@keyframes br-progress {
  0% {
    transform: translateX(-120%);
  }
  100% {
    transform: translateX(280%);
  }
}

@media (max-width: 960px) {
  .br-header,
  .br-workspace {
    grid-template-columns: 1fr;
  }

  .br-workspace {
    height: auto;
    min-height: 0;
    gap: 12px;
  }

  .br-pane {
    min-height: 320px;
  }

  .br-bridge {
    min-height: 48px;
  }

  .br-bridge__rail {
    top: 50%;
    left: 20%;
    right: 20%;
  }

  .br-actions {
    align-items: stretch;
  }

  .br-actions__btns,
  .br-btn {
    width: 100%;
  }
}

@media (prefers-reduced-motion: reduce) {
  .br-scan__beam,
  .br-status__pulse,
  .br-steps li.is-active::before,
  .br-bridge__dot,
  .br-bridge__orb,
  .br-loader__ring,
  .br-loader__core,
  .br-progress span,
  .br-spin,
  .br-frame img {
    animation: none !important;
    transition: none !important;
  }

  .br-frame.is-checker img {
    opacity: 1;
    transform: none;
    filter: none;
  }
}
</style>

// apps/web-react/src/views/BackgroundRemoveView.jsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useAuth } from "../auth/AuthContext.jsx";
import { useIsDark } from "../hooks/useIsDark.js";
import { AuthenticatedImage } from "../components/AuthenticatedImage.jsx";
import {
  compressImageFile,
  downloadBlob,
  formatBytes,
  outputFilename,
  savingsPercent,
  terminateCompressWorker,
} from "@legacy/features/image-compress/compressEngine.js";
import { taskCoverUrl, taskOriginalUrl } from "@legacy/features/creator-hub/taskMedia.js";
import { fetchRuntimeConfig } from "@legacy/services/runtimeConfig.js";
import { getWallet, updateProfile } from "@legacy/services/meApi.js";
import { listTasks } from "@legacy/services/tasksApi.js";
import { removeImageBackground, uploadAiInputFile } from "@legacy/services/aiWallpaper.js";
import {
  downloadAuthenticatedMedia,
  fetchAuthenticatedMediaBlob,
} from "@legacy/services/authenticatedMedia.js";
import { formatPoints } from "@legacy/services/billingApi.js";
import notificationService from "@legacy/services/notification.js";
import "@legacy/views/BackgroundRemoveView.vue?react-style";
import "@legacy/features/ai-shared/AiCostConfirmDialog.vue?react-style";
import "./BackgroundRemoveView.css";

const STAGE_META = {
  idle: { label: "等待上传", detail: "选择一张图片开始抠图" },
  ready: { label: "准备就绪", detail: "点击下方按钮移除背景" },
  uploading: { label: "上传原图", detail: "正在安全上传到处理通道" },
  queued: { label: "排队中", detail: "任务已创建，等待算力分配" },
  running: { label: "智能抠图", detail: "正在分离主体与背景" },
  succeeded: { label: "处理完成", detail: "透明 PNG 已就绪，可本页压缩后下载" },
  failed: { label: "处理失败", detail: "可更换图片或重试" },
};
const STAGE_ORDER = ["uploading", "queued", "running", "succeeded"];
const HISTORY_LIMIT = 24;

function imageTools(config = {}) {
  const feature = config.features?.["ai.imageTools"] || {};
  const payload = feature.config && typeof feature.config === "object" ? feature.config : {};
  const models = Array.isArray(payload.backgroundRemovalModels)
    ? payload.backgroundRemovalModels.filter((model) => model?.id)
    : [];
  return {
    enabled: feature.enabled !== false,
    models,
    active: models.find((model) => model.default === true) || models[0] || null,
  };
}

function stageFromTask(task = {}) {
  const status = String(task.status || "").toLowerCase();
  if (["queued", "running", "succeeded"].includes(status)) return status;
  if (["failed", "canceled", "cancelled"].includes(status)) return "failed";
  return "queued";
}

function historyTime(value) {
  const date = new Date(value || "");
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleString("zh-CN", {
    month: "numeric",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function CostConfirmDialog({ cost, light, onCancel, onConfirm }) {
  const [skipEveryTime, setSkipEveryTime] = useState(false);
  useEffect(() => {
    if (cost) setSkipEveryTime(false);
  }, [cost]);
  if (!cost) return null;
  const insufficient = cost.available != null && cost.available < cost.total;
  return createPortal(
    <div
      className={`ai-cost-confirm-layer${light ? " is-light" : ""}`}
      onMouseDown={(event) => event.target === event.currentTarget && onCancel()}
    >
      <section
        className="ai-cost-confirm-panel is-credits"
        role="dialog"
        aria-modal="true"
        aria-labelledby="background-cost-title"
      >
        <header className="ai-cost-confirm-head">
          <span className="ai-cost-confirm-icon"><i className="bi bi-coin" /></span>
          <div className="ai-cost-confirm-titles">
            <span className="ai-cost-confirm-eyebrow">背景移除</span>
            <h5 id="background-cost-title">确认生成费用</h5>
          </div>
          <button type="button" className="ai-cost-confirm-close" aria-label="关闭费用确认" onClick={onCancel}>
            <i className="bi bi-x-lg" />
          </button>
        </header>
        <p className="ai-cost-confirm-summary">提交后先冻结预计费用，任务完成后按实际生成结果结算。</p>
        <div className="ai-cost-confirm-card">
          <div className="ai-cost-confirm-total">
            <div className="ai-cost-confirm-total__copy"><span>本次预计</span><small>{cost.unit} 积分 / 张 × 1 张</small></div>
            <strong>{cost.total > 0 ? `${cost.total} 积分` : "按实际用量结算"}</strong>
          </div>
          <div className="ai-cost-confirm-balance">
            <div><span>当前可用</span><strong>{cost.available == null ? "读取中" : `${cost.available} 积分`}</strong></div>
            <i className="bi bi-arrow-right" />
            <div className={insufficient ? "danger" : ""}><span>支付后余额</span><strong>{cost.available == null ? "待计算" : insufficient ? "余额不足" : `${cost.available - cost.total} 积分`}</strong></div>
          </div>
        </div>
        {insufficient && <p className="ai-cost-confirm-warn is-danger"><i className="bi bi-exclamation-circle" />钱包余额不足，请兑换积分后再提交任务。</p>}
        <footer className="ai-cost-confirm-footer">
          <label className="ai-cost-confirm-preference">
            <input type="checkbox" checked={skipEveryTime} onChange={(event) => setSkipEveryTime(event.target.checked)} />
            <span>不再每次确认</span>
          </label>
          <div className="ai-cost-confirm-actions">
            <button type="button" className="ai-cost-confirm-btn ghost" onClick={onCancel}>取消</button>
            <button type="button" className="ai-cost-confirm-btn primary" disabled={insufficient} onClick={() => onConfirm({ skipEveryTime })}>确认</button>
          </div>
        </footer>
      </section>
    </div>,
    document.body,
  );
}

export function BackgroundRemoveView() {
  const auth = useAuth();
  const isDark = useIsDark();
  const fileInputRef = useRef(null);
  const mountedRef = useRef(true);
  const sourcePreviewRef = useRef("");
  const taskControllerRef = useRef(null);
  const historyControllerRef = useRef(null);
  const compressControllerRef = useRef(null);
  const compressTokenRef = useRef(0);
  const resultCacheRef = useRef({ url: "", file: null });
  const [sourceFile, setSourceFile] = useState(null);
  const [sourcePreview, setSourcePreview] = useState("");
  const [resultUrl, setResultUrl] = useState("");
  const [processing, setProcessing] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [cost, setCost] = useState(null);
  const [stage, setStage] = useState("idle");
  const [errorMessage, setErrorMessage] = useState("");
  const [resultReveal, setResultReveal] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [historyItems, setHistoryItems] = useState([]);
  const [historyError, setHistoryError] = useState("");
  const [activeHistoryId, setActiveHistoryId] = useState("");
  const [latestFromHistory, setLatestFromHistory] = useState(false);
  const [compressFormat, setCompressFormat] = useState("png");
  const [compressBusy, setCompressBusy] = useState(false);
  const [compressError, setCompressError] = useState("");
  const [compressStats, setCompressStats] = useState(null);
  const [toolState, setToolState] = useState({ enabled: true, models: [], active: null });

  sourcePreviewRef.current = sourcePreview;
  const activeTool = toolState.active;
  const unitPrice = Math.max(0, Number(activeTool?.pricePoints || 0));
  const canRun = Boolean(sourceFile && activeTool && !processing);
  const meta = STAGE_META[stage] || STAGE_META.idle;
  const stageIndex = stage === "failed" ? 1 : ["ready", "idle"].includes(stage) ? -1 : STAGE_ORDER.indexOf(stage);
  const tone = stage === "failed" ? "danger" : stage === "succeeded" ? "success" : processing ? "busy" : sourceFile ? "ready" : "idle";
  const compressSavings = compressStats
    ? compressStats.afterBytes >= compressStats.beforeBytes
      ? "已是较优体积"
      : `已减小 ${savingsPercent(compressStats.beforeBytes, compressStats.afterBytes)}%`
    : "";

  const releasePreview = useCallback(() => {
    setSourcePreview((current) => {
      if (current.startsWith("blob:")) URL.revokeObjectURL(current);
      return "";
    });
  }, []);

  const resetCompression = useCallback(() => {
    compressTokenRef.current += 1;
    compressControllerRef.current?.abort();
    compressControllerRef.current = null;
    setCompressBusy(false);
    setCompressError("");
    setCompressStats(null);
    resultCacheRef.current = { url: "", file: null };
  }, []);

  const showResult = useCallback((url, { historyId = "", fromHistory = false } = {}) => {
    if (!url || !mountedRef.current) return false;
    setResultUrl(url);
    setActiveHistoryId(historyId);
    setLatestFromHistory(fromHistory);
    setErrorMessage("");
    setStage("succeeded");
    setResultReveal(false);
    requestAnimationFrame(() => mountedRef.current && setResultReveal(true));
    return true;
  }, []);

  const selectFile = useCallback((file, { notifyPaste = false } = {}) => {
    if (!file || processing) return;
    if (!String(file.type || "").startsWith("image/")) {
      notificationService.warning("请选择 PNG、JPG 或 WebP 图片");
      return;
    }
    if (file.size > 15 * 1024 * 1024) {
      notificationService.warning("图片不能超过 15MB");
      return;
    }
    releasePreview();
    const preview = URL.createObjectURL(file);
    setSourceFile(file);
    setSourcePreview(preview);
    setResultUrl("");
    setResultReveal(false);
    setErrorMessage("");
    setActiveHistoryId("");
    setLatestFromHistory(false);
    resetCompression();
    setStage("ready");
    if (notifyPaste) notificationService.success("已粘贴截图");
  }, [processing, releasePreview, resetCompression]);

  const clearImage = useCallback(() => {
    if (processing) return;
    releasePreview();
    setSourceFile(null);
    setResultUrl("");
    setResultReveal(false);
    setErrorMessage("");
    setActiveHistoryId("");
    setLatestFromHistory(false);
    resetCompression();
    setStage("idle");
  }, [processing, releasePreview, resetCompression]);

  const loadHistory = useCallback(async ({ silent = false, showLatest = false } = {}) => {
    if (!auth.isAuthenticated) {
      setHistoryItems([]);
      setHistoryError(silent ? "" : "登录后可查看抠图历史");
      return [];
    }
    historyControllerRef.current?.abort();
    const controller = new AbortController();
    historyControllerRef.current = controller;
    setHistoryLoading(true);
    if (!silent) setHistoryError("");
    try {
      const { items } = await listTasks({
        type: "background_remove",
        status: "succeeded",
        limit: HISTORY_LIMIT,
        signal: controller.signal,
      });
      const next = (items || []).filter((task) => taskOriginalUrl(task) || taskCoverUrl(task));
      if (!mountedRef.current || controller.signal.aborted) return [];
      setHistoryItems(next);
      if (showLatest && !sourceFile && !resultUrl && next[0]) {
        showResult(taskOriginalUrl(next[0]) || taskCoverUrl(next[0]), {
          historyId: next[0].id,
          fromHistory: true,
        });
      }
      return next;
    } catch (error) {
      if (error?.name === "AbortError") return [];
      if (mountedRef.current) {
        setHistoryError(error?.message || "历史记录读取失败");
        if (!silent) notificationService.error(error?.message || "历史记录读取失败");
      }
      return [];
    } finally {
      if (mountedRef.current && historyControllerRef.current === controller) setHistoryLoading(false);
    }
  }, [auth.isAuthenticated, resultUrl, showResult, sourceFile]);

  useEffect(() => {
    mountedRef.current = true;
    let disposed = false;
    fetchRuntimeConfig()
      .then((config) => !disposed && setToolState(imageTools(config)))
      .catch(() => undefined);
    void loadHistory({ silent: true, showLatest: true });
    return () => {
      disposed = true;
      mountedRef.current = false;
      taskControllerRef.current?.abort();
      historyControllerRef.current?.abort();
      compressControllerRef.current?.abort();
      const preview = sourcePreviewRef.current;
      if (preview.startsWith("blob:")) URL.revokeObjectURL(preview);
      terminateCompressWorker();
    };
    // Initial history restore is intentionally one-shot.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const onPaste = (event) => {
      if (processing || cost || historyOpen) return;
      if (event.target?.closest?.("input, textarea, select, [contenteditable='true']")) return;
      const image = Array.from(event.clipboardData?.items || [])
        .filter((item) => item.kind === "file" && item.type?.startsWith("image/"))
        .map((item) => item.getAsFile())
        .find(Boolean);
      if (!image) return;
      event.preventDefault();
      const ext = image.type.includes("jpeg") ? "jpg" : image.type.includes("webp") ? "webp" : "png";
      const named = image.name && image.name !== "image.png"
        ? image
        : new File([image], `paste-${Date.now()}.${ext}`, { type: image.type || "image/png" });
      selectFile(named, { notifyPaste: true });
    };
    window.addEventListener("paste", onPaste);
    return () => window.removeEventListener("paste", onPaste);
  }, [cost, historyOpen, processing, selectFile]);

  const loadResultFile = useCallback(async (signal) => {
    if (!resultUrl) throw new Error("还没有抠图结果");
    if (resultCacheRef.current.url === resultUrl && resultCacheRef.current.file) {
      return resultCacheRef.current.file;
    }
    const blob = await fetchAuthenticatedMediaBlob(resultUrl, { cache: "no-store", signal });
    if (signal?.aborted) throw new DOMException("Aborted", "AbortError");
    const file = new File([blob], `background-removed-${Date.now()}.png`, {
      type: blob.type || "image/png",
    });
    resultCacheRef.current = { url: resultUrl, file };
    return file;
  }, [resultUrl]);

  const prepareCompression = useCallback(async () => {
    if (!resultUrl || processing) return null;
    const token = ++compressTokenRef.current;
    compressControllerRef.current?.abort();
    const controller = new AbortController();
    compressControllerRef.current = controller;
    setCompressBusy(true);
    setCompressError("");
    try {
      const file = await loadResultFile(controller.signal);
      const result = await compressImageFile(file, {
        format: compressFormat,
        intensity: "balanced",
        keepIfLarger: true,
        signal: controller.signal,
      });
      if (!mountedRef.current || token !== compressTokenRef.current || controller.signal.aborted) return null;
      const stats = {
        beforeBytes: result.beforeBytes,
        afterBytes: result.afterBytes,
        format: result.format,
        blob: result.blob,
        keptOriginal: result.keptOriginal,
        filename: outputFilename(file.name, result.format),
      };
      setCompressStats(stats);
      return stats;
    } catch (error) {
      if (error?.name === "AbortError") return null;
      if (mountedRef.current && token === compressTokenRef.current) {
        setCompressStats(null);
        setCompressError(error?.message || "压缩预览失败");
      }
      return null;
    } finally {
      if (mountedRef.current && token === compressTokenRef.current) setCompressBusy(false);
    }
  }, [compressFormat, loadResultFile, processing, resultUrl]);

  useEffect(() => {
    resetCompression();
    if (resultUrl) void prepareCompression();
  }, [compressFormat, prepareCompression, resetCompression, resultUrl]);

  const executeRemoval = useCallback(async () => {
    if (!canRun) return;
    setCost(null);
    taskControllerRef.current?.abort();
    const controller = new AbortController();
    taskControllerRef.current = controller;
    setProcessing(true);
    setResultUrl("");
    setResultReveal(false);
    setErrorMessage("");
    setActiveHistoryId("");
    setLatestFromHistory(false);
    setStage("uploading");
    try {
      const uploadedUrl = await uploadAiInputFile(sourceFile, { signal: controller.signal });
      if (controller.signal.aborted) throw new DOMException("Aborted", "AbortError");
      setStage("queued");
      const response = await removeImageBackground(uploadedUrl, activeTool.id, {
        signal: controller.signal,
        onUpdate(task) {
          if (mountedRef.current && !controller.signal.aborted) setStage(stageFromTask(task));
        },
      });
      const completed = response?.task || null;
      const output =
        response?.result?.outputs?.[0] ||
        response?.job?.originalMediaUrls?.[0] ||
        taskOriginalUrl(completed) ||
        "";
      if (!output) throw new Error("任务已完成，但没有返回图片");
      showResult(output, { historyId: completed?.id || "" });
      if (completed) {
        setHistoryItems((current) => [completed, ...current.filter((item) => item.id !== completed.id)].slice(0, HISTORY_LIMIT));
      } else {
        void loadHistory({ silent: true });
      }
      notificationService.success("背景已移除");
    } catch (error) {
      if (error?.name !== "AbortError" && mountedRef.current) {
        setStage("failed");
        setErrorMessage(error?.message || "背景移除失败");
        notificationService.error(error?.message || "背景移除失败");
      }
    } finally {
      if (mountedRef.current && taskControllerRef.current === controller) setProcessing(false);
    }
  }, [activeTool, canRun, loadHistory, showResult, sourceFile]);

  const requestRemoval = useCallback(async () => {
    if (!canRun) return;
    if (auth.user?.requireCostConfirm === false) {
      await executeRemoval();
      return;
    }
    let available = null;
    try {
      const wallet = await getWallet();
      const value = Number(wallet?.availableCents ?? wallet?.balanceCents ?? wallet?.availablePoints);
      if (Number.isFinite(value)) available = Math.max(0, value);
    } catch { /* the task service remains authoritative */ }
    setCost({ unit: unitPrice, total: unitPrice, available });
  }, [auth.user?.requireCostConfirm, canRun, executeRemoval, unitPrice]);

  const confirmRemovalCost = useCallback(async ({ skipEveryTime = false } = {}) => {
    setCost(null);
    if (skipEveryTime) {
      try {
        const result = await updateProfile({ requireCostConfirm: false });
        auth.setUser((current) => ({
          ...(current || {}),
          ...(result?.user || { requireCostConfirm: false }),
        }));
      } catch {
        // Preference persistence must not block the confirmed removal task.
      }
    }
    await executeRemoval();
  }, [auth, executeRemoval]);

  const downloadCompressed = useCallback(async () => {
    if (!resultUrl || compressBusy || processing) return;
    try {
      const stats = compressStats?.blob && compressStats.format === compressFormat
        ? compressStats
        : await prepareCompression();
      if (!stats?.blob) throw new Error(compressError || "压缩失败");
      downloadBlob(stats.blob, stats.filename);
      notificationService.success(
        stats.keptOriginal || stats.afterBytes >= stats.beforeBytes
          ? "已下载（体积已接近最优）"
          : `已下载压缩结果，减小 ${savingsPercent(stats.beforeBytes, stats.afterBytes)}%`,
      );
    } catch (error) {
      notificationService.error(error?.message || "压缩下载失败");
    }
  }, [compressBusy, compressError, compressFormat, compressStats, prepareCompression, processing, resultUrl]);

  const openHistory = () => {
    setHistoryOpen(true);
    if (!historyItems.length) void loadHistory();
  };
  const selectHistory = (task) => {
    if (processing) return;
    const url = taskOriginalUrl(task) || taskCoverUrl(task);
    if (!url) return;
    showResult(url, { historyId: task.id, fromHistory: true });
    setHistoryOpen(false);
  };

  return (
    <main className={`br${isDark ? " is-dark" : ""}${processing ? " is-processing" : ""}${stage === "succeeded" ? " is-done" : ""}${stage === "failed" ? " is-failed" : ""}`}>
      <div className="br-glow" aria-hidden="true" />
      <header className="br-header">
        <div className="br-header__copy">
          <span className="br-kicker"><i className="bi bi-scissors" />图片工具</span>
          <h1>背景移除</h1>
          <p>上传商品或人像图，一键保留主体；抠图完成后可在本页直接压缩下载，无需跳转。</p>
          <div className="br-meta">
            <span className="br-chip"><i className="bi bi-filetype-png" />透明 PNG</span>
            <span className="br-chip"><i className="bi bi-download" />本页压缩下载</span>
            <span className="br-chip"><i className="bi bi-image" />最大 15MB</span>
            <span className="br-chip"><i className="bi bi-clipboard-check" />支持粘贴截图</span>
            {activeTool ? <span className="br-chip is-price"><i className="bi bi-coin" />{formatPoints(unitPrice)} / 张</span> : <span className="br-chip is-warn">工具未开放</span>}
          </div>
        </div>
        <aside className="br-status" data-tone={tone} aria-live="polite">
          <div className="br-status__pulse" />
          <div className="br-status__copy"><small>当前状态</small><strong>{meta.label}</strong><p>{errorMessage || meta.detail}</p></div>
          <ol className="br-steps" aria-label="处理进度">
            {STAGE_ORDER.map((key, index) => <li key={key} className={`${stageIndex > index || (stage === "succeeded" && index === STAGE_ORDER.length - 1) ? "is-done" : ""}${stageIndex === index ? " is-active" : ""}`}><span>{STAGE_META[key].label}</span></li>)}
          </ol>
        </aside>
      </header>

      <section className="br-workspace" aria-label="背景移除工作区">
        <div className={`br-pane${dragging ? " is-dragging" : ""}${sourcePreview ? " has-image" : ""}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={(event) => { event.preventDefault(); setDragging(false); }} onDrop={(event) => { event.preventDefault(); setDragging(false); selectFile(event.dataTransfer.files?.[0]); }}>
          <div className="br-pane__head"><strong>原图</strong>{sourceFile && <span>{sourceFile.name}</span>}{sourceFile && <button type="button" className="br-ghost" disabled={processing} onClick={clearImage}><i className="bi bi-trash3" />清空</button>}</div>
          {!sourcePreview ? <button type="button" className="br-dropzone" onClick={() => fileInputRef.current?.click()}><span className="br-dropzone__icon"><i className="bi bi-cloud-arrow-up" /></span><strong>上传图片</strong><span>点击选择、拖入文件，或按 Ctrl/⌘ + V 粘贴截图</span></button> : <div className="br-frame"><img src={sourcePreview} alt="待处理原图" /><>{processing && <div className="br-scan"><span className="br-scan__beam" /><span className="br-scan__veil" /></div>}</><button type="button" className="br-frame__action" disabled={processing} onClick={() => fileInputRef.current?.click()}><i className="bi bi-arrow-repeat" />更换</button></div>}
        </div>
        <div className="br-bridge" aria-hidden="true"><div className="br-bridge__rail">{Array.from({ length: 5 }, (_, index) => <span key={index} className="br-bridge__dot" />)}</div><div className="br-bridge__orb"><i className={`bi ${processing ? "bi-hourglass-split" : resultUrl ? "bi-check-lg" : "bi-scissors"}`} /></div></div>
        <div className={`br-pane is-result${resultUrl ? " has-result" : ""}`}>
          <div className="br-pane__head"><strong>透明结果</strong>{resultUrl ? <span>{latestFromHistory ? "最近一张结果" : "PNG · 透明通道"}</span> : processing ? <span>处理中</span> : null}<button type="button" className="br-ghost" onClick={openHistory}><i className="bi bi-clock-history" />查看历史</button></div>
          {resultUrl ? <div className={`br-frame is-checker${resultReveal ? " is-reveal" : ""}`}><AuthenticatedImage className="br-result-image" src={resultUrl} alt="背景移除结果" loading="eager" maxDimension={1600} /><div className="br-frame__badge"><i className="bi bi-check2-circle" />{latestFromHistory ? "历史结果" : "已抠图"}</div></div> : <div className={`br-empty${processing ? " is-busy" : ""}`}><div className="br-loader"><span className="br-loader__ring" /><span className="br-loader__ring is-delay" /><span className="br-loader__core"><i className={`bi ${processing ? "bi-magic" : "bi-person-bounding-box"}`} /></span></div><strong>{processing ? meta.label : "结果将在这里显示"}</strong><p>{processing ? meta.detail : "移除背景后可预览、本页压缩并下载"}</p>{processing && <div className="br-progress"><span /></div>}</div>}
        </div>
      </section>

      {resultUrl && <section className="br-compress" aria-label="本页压缩下载"><div className="br-compress__copy"><strong><i className="bi bi-arrows-collapse" />抠图后压缩</strong><p>{compressBusy ? "正在本地压缩预览…" : compressError ? compressError : compressStats ? <>{formatBytes(compressStats.beforeBytes)} → {formatBytes(compressStats.afterBytes)}{compressSavings ? ` · ${compressSavings}` : ""} · 本地处理，不离开本页</> : "可直接压缩透明结果后再下载"}</p></div><div className="br-compress__controls"><div className="br-compress__formats" role="group" aria-label="压缩格式"><button type="button" className={`br-seg${compressFormat === "png" ? " is-on" : ""}`} disabled={compressBusy || processing} onClick={() => setCompressFormat("png")}>PNG 无损</button><button type="button" className={`br-seg${compressFormat === "webp" ? " is-on" : ""}`} disabled={compressBusy || processing} onClick={() => setCompressFormat("webp")}>WebP</button></div><button type="button" className="br-btn is-primary" disabled={!resultUrl || compressBusy || processing} onClick={downloadCompressed}><i className={`bi ${compressBusy ? "bi-arrow-repeat br-spin" : "bi-download"}`} />{compressBusy ? "压缩中…" : "压缩并下载"}</button></div></section>}

      <footer className="br-actions"><div className="br-actions__hint">{!activeTool ? "后台尚未开放背景移除工具" : processing ? "请保持页面打开，完成后可本页压缩下载" : resultUrl && latestFromHistory ? "正在显示最近一张抠图结果；可本页压缩，或上传新图继续处理" : resultUrl ? "结果已生成，可本页压缩下载，无需跳转图片压缩页" : "支持拖入与粘贴截图；上传后按张扣积分，失败或取消会自动返还"}</div><div className="br-actions__btns"><button type="button" className="br-btn is-primary" disabled={!canRun} onClick={requestRemoval}><i className={`bi ${processing ? "bi-arrow-repeat br-spin" : "bi-magic"}`} />{processing ? "处理中…" : stage === "failed" ? "重新移除背景" : "移除背景"}</button><button type="button" className="br-btn is-secondary" disabled={!resultUrl || processing} onClick={() => downloadAuthenticatedMedia(resultUrl, `background-removed-${Date.now()}.png`)}><i className="bi bi-download" />原图下载</button><button type="button" className="br-btn is-secondary" disabled={!resultUrl || compressBusy || processing} onClick={downloadCompressed}><i className="bi bi-download" />压缩下载</button></div></footer>

      {historyOpen && createPortal(<div className={`br-history${isDark ? " is-dark" : ""}`} role="dialog" aria-modal="true" aria-label="抠图历史"><button type="button" className="br-history__backdrop" aria-label="关闭历史" onClick={() => setHistoryOpen(false)} /><aside className="br-history__panel"><header className="br-history__head"><div><strong>抠图历史</strong><span>{historyItems.length ? `${historyItems.length} 张` : "暂无"}</span></div><div className="br-history__head-actions"><button type="button" className="br-ghost" disabled={historyLoading} onClick={() => loadHistory()}><i className={`bi bi-arrow-clockwise${historyLoading ? " br-spin" : ""}`} />刷新</button><button type="button" className="br-ghost" onClick={() => setHistoryOpen(false)}><i className="bi bi-x-lg" />关闭</button></div></header>{historyLoading && !historyItems.length ? <div className="br-history__empty"><i className="bi bi-arrow-repeat br-spin" /><p>正在加载历史…</p></div> : historyError && !historyItems.length ? <div className="br-history__empty"><p>{historyError}</p><button type="button" className="br-btn is-secondary" onClick={() => loadHistory()}>重新加载</button></div> : !historyItems.length ? <div className="br-history__empty"><i className="bi bi-images" /><strong>还没有抠图记录</strong><p>完成一次背景移除后，结果会出现在这里</p></div> : <div className="br-history__grid" role="list">{historyItems.map((item) => <button key={item.id} type="button" className={`br-history__card${activeHistoryId === item.id ? " is-active" : ""}`} role="listitem" disabled={processing} onClick={() => selectHistory(item)}><span className="br-history__thumb is-checker"><AuthenticatedImage src={taskCoverUrl(item)} alt="历史抠图结果" maxDimension={320} /></span><span className="br-history__meta"><strong>{historyTime(item.finishedAt || item.createdAt) || "已完成"}</strong><small>点击查看</small></span></button>)}</div>}</aside></div>, document.body)}

      <input ref={fileInputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={(event) => { selectFile(event.target.files?.[0]); event.target.value = ""; }} />
      <CostConfirmDialog cost={cost} light={!isDark} onCancel={() => setCost(null)} onConfirm={confirmRemovalCost} />
    </main>
  );
}
