// apps/web-react/src/views/PromptLibraryView.jsx
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { createPortal } from "react-dom";
import { useNavigate } from "react-router";
import { useAuth } from "../auth/AuthContext.jsx";
import { useAuthPrompt } from "../auth/AuthPromptContext.jsx";
import { useVirtualMasonryFeed } from "../features/prompts/useVirtualMasonryFeed.js";
import {
  listPromptCategories,
  listPromptLibrary,
  recordPromptEngagement,
} from "@react/legacy-modules/services/promptLibrary.js";
import notificationService from "@react/legacy-modules/services/notification.js";
import {
  PROMPT_TASK_TYPES,
  stashPendingPrompt,
  studioRouteForTaskType,
} from "@react/legacy-modules/features/creator-hub/studioTools.js";
import { setBodyScrollLock } from "@react/legacy-modules/utils/bodyScrollLock.js";
import "@react/legacy-static/features/creator-hub/creator-hub.css";

const PREVIEW_SCROLL_LOCK = "prompt-library-preview";
const SCOPE_CATEGORIES = [
  { id: "all", label: "全部" },
  { id: "today", label: "今日最新", scope: "today" },
  { id: "favorites", label: "我的收藏", scope: "favorites" },
];

function categoryId(category) {
  return String(category?.key || category?.id || "");
}

export function PromptLibraryView() {
  const navigate = useNavigate();
  const auth = useAuth();
  const { requestAuth } = useAuthPrompt();
  const [items, setItems] = useState([]);
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(false);
  const [search, setSearch] = useState("");
  const [activeType, setActiveType] = useState("t2i");
  const [activeCategory, setActiveCategory] = useState("all");
  const [preview, setPreview] = useState(null);
  const requestIdRef = useRef(0);
  const loadSentinelRef = useRef(null);
  const previewPanelRef = useRef(null);
  const previewInertiaCleanupRef = useRef(null);

  const stopPreviewInertiaGuard = useCallback(() => {
    previewInertiaCleanupRef.current?.();
    previewInertiaCleanupRef.current = null;
  }, []);

  const startPreviewInertiaGuard = useCallback(
    (duration = 0, { allowPreviewScroll = false } = {}) => {
      stopPreviewInertiaGuard();
      const shouldBlock = (event) => {
        if (!allowPreviewScroll) return true;
        const scroller =
          event.target?.closest?.(".ch-preview__media") ||
          event.target?.closest?.(".ch-preview__mid");
        if (!scroller) return true;
        if (event.type === "touchmove") return false;
        const { scrollTop, scrollHeight, clientHeight } = scroller;
        const delta = Number(event.deltaY) || 0;
        if (scrollHeight <= clientHeight + 1) return true;
        const atTop = scrollTop <= 0;
        const atBottom = scrollTop + clientHeight >= scrollHeight - 1;
        return (atTop && delta < 0) || (atBottom && delta > 0);
      };
      const blockOverscroll = (event) => {
        if (shouldBlock(event)) event.preventDefault();
      };
      document.addEventListener("wheel", blockOverscroll, {
        passive: false,
        capture: true,
      });
      document.addEventListener("touchmove", blockOverscroll, {
        passive: false,
        capture: true,
      });
      const timer = duration
        ? window.setTimeout(() => stopPreviewInertiaGuard(), duration)
        : 0;
      previewInertiaCleanupRef.current = () => {
        if (timer) window.clearTimeout(timer);
        document.removeEventListener("wheel", blockOverscroll, { capture: true });
        document.removeEventListener("touchmove", blockOverscroll, {
          capture: true,
        });
      };
    },
    [stopPreviewInertiaGuard],
  );

  const categoryMeta = useMemo(() => {
    const scopeIds = new Set(SCOPE_CATEGORIES.map((item) => item.id));
    return [
      ...SCOPE_CATEGORIES.filter(
        (item) => item.scope !== "favorites" || auth.isAuthenticated,
      ),
      ...categories
        .filter((item) => !scopeIds.has(categoryId(item)))
        .map((item) => ({ ...item, id: categoryId(item) })),
    ];
  }, [auth.isAuthenticated, categories]);

  useEffect(() => {
    if (!categoryMeta.some((item) => item.id === activeCategory)) {
      setActiveCategory("all");
    }
  }, [activeCategory, categoryMeta]);

  const activeScope =
    SCOPE_CATEGORIES.find((item) => item.id === activeCategory)?.scope || "";
  const categoryParam = activeScope || activeCategory === "all" ? "" : activeCategory;

  useEffect(() => {
    let disposed = false;
    listPromptCategories({ type: activeType })
      .then((rows) => {
        if (!disposed) setCategories(Array.isArray(rows) ? rows : []);
      })
      .catch(() => {
        if (!disposed) setCategories([]);
      });
    return () => {
      disposed = true;
    };
  }, [activeType]);

  const loadPrompts = useCallback(
    async ({ reset = true } = {}) => {
      if (!reset && (loading || loadingMore || !hasMore)) return;
      const requestId = reset ? ++requestIdRef.current : requestIdRef.current;
      const nextPage = reset ? 1 : page + 1;
      if (reset) setLoading(true);
      else setLoadingMore(true);
      try {
        const response = await listPromptLibrary(activeType, {
          pageNumber: nextPage,
          pageSize: 24,
          category: categoryParam,
          scope: activeScope,
        });
        if (requestId !== requestIdRef.current) return;
        setItems((current) =>
          reset ? response.items || [] : [...current, ...(response.items || [])],
        );
        setPage(nextPage);
        setHasMore(Boolean(response.hasMore));
      } catch (error) {
        if (reset) setItems([]);
        notificationService.error(error?.message || "提示词读取失败");
      } finally {
        if (requestId === requestIdRef.current) {
          setLoading(false);
          setLoadingMore(false);
        }
      }
    }, [activeScope, activeType, categoryParam, hasMore, loading, loadingMore, page]);

  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "auto" });
    void loadPrompts({ reset: true });
    // Reset loads are intentionally keyed only by the selected server filters.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeType, activeCategory]);

  useEffect(() => {
    const sentinel = loadSentinelRef.current;
    if (!sentinel || !hasMore || typeof IntersectionObserver === "undefined") {
      return undefined;
    }
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting)) {
          void loadPrompts({ reset: false });
        }
      },
      { root: null, rootMargin: "1200px 0px", threshold: 0 },
    );
    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [hasMore, loadPrompts]);

  useEffect(() => {
    document.documentElement.classList.add("creator-hub-sticky-page");
    return () => {
      document.documentElement.classList.remove("creator-hub-sticky-page");
      stopPreviewInertiaGuard();
      setBodyScrollLock(PREVIEW_SCROLL_LOCK, false);
    };
  }, [stopPreviewInertiaGuard]);

  const filteredItems = useMemo(() => {
    const query = search.trim().toLowerCase();
    if (!query) return items;
    return items.filter((item) =>
      `${item.title || ""} ${item.prompt || ""} ${(item.tags || []).join(" ")}`
        .toLowerCase()
        .includes(query),
    );
  }, [items, search]);

  const masonryItems = useMemo(
    () =>
      filteredItems.map((item, index) => ({
        key: String(item.id || index),
        item,
        index,
        aspect:
          Number(item.coverWidth) > 0 && Number(item.coverHeight) > 0
            ? `${item.coverWidth} / ${item.coverHeight}`
            : "3 / 4",
        cover: item.coverUrl || item.imageUrl || "",
      })),
    [filteredItems],
  );
  const getEntryAspect = useCallback((entry) => entry.aspect, []);
  const masonry = useVirtualMasonryFeed({
    items: masonryItems,
    fallbackAspect: 3 / 4,
    bodyHeight: 178,
    minColumnWidth: 260,
    maxColumns: 12,
    overscan: 960,
    getAspect: getEntryAspect,
  });

  const activeTypeLabel =
    PROMPT_TASK_TYPES.find((item) => item.id === activeType)?.label || "文生图";
  const previewIndex = preview
    ? filteredItems.findIndex((item) => String(item.id) === String(preview.id))
    : -1;
  const hasPreviewPrev = previewIndex > 0;
  const hasPreviewNext =
    previewIndex >= 0 && previewIndex < filteredItems.length - 1;

  const openPreview = useCallback(
    (item) => {
      stopPreviewInertiaGuard();
      setPreview(item);
    },
    [stopPreviewInertiaGuard],
  );
  const closePreview = useCallback(() => {
    const root = previewPanelRef.current;
    for (const element of [
      root?.querySelector(".ch-preview__media"),
      root?.querySelector(".ch-preview__mid"),
    ]) {
      if (!element) continue;
      element.style.overflow = "hidden";
      element.scrollTop = element.scrollTop;
    }
    setPreview(null);
    startPreviewInertiaGuard(450, { allowPreviewScroll: false });
  }, [startPreviewInertiaGuard]);
  const showPreviewAt = useCallback(
    (index) => {
      const item = filteredItems[index];
      if (!item) return;
      setPreview(item);
      requestAnimationFrame(() => {
        const root = previewPanelRef.current;
        const media = root?.querySelector(".ch-preview__media");
        const mid = root?.querySelector(".ch-preview__mid");
        if (media) media.scrollTop = 0;
        if (mid) mid.scrollTop = 0;
      });
    },
    [filteredItems],
  );

  useEffect(() => {
    if (!preview) return undefined;
    setBodyScrollLock(PREVIEW_SCROLL_LOCK, true, { freezeViewport: false });
    startPreviewInertiaGuard(0, { allowPreviewScroll: true });
    const onKeyDown = (event) => {
      if (event.key === "Escape") {
        event.preventDefault();
        closePreview();
      } else if (event.key === "ArrowLeft" && hasPreviewPrev) {
        event.preventDefault();
        showPreviewAt(previewIndex - 1);
      } else if (event.key === "ArrowRight" && hasPreviewNext) {
        event.preventDefault();
        showPreviewAt(previewIndex + 1);
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      setBodyScrollLock(PREVIEW_SCROLL_LOCK, false);
    };
  }, [
    closePreview,
    hasPreviewNext,
    hasPreviewPrev,
    preview,
    previewIndex,
    showPreviewAt,
    startPreviewInertiaGuard,
  ]);

  async function copyPrompt(item) {
    const prompt = String(item?.prompt || "").trim();
    if (!prompt) {
      notificationService.info("没有可复制的提示词");
      return;
    }
    try {
      await navigator.clipboard.writeText(prompt);
      notificationService.success("提示词已复制");
    } catch {
      notificationService.error("复制失败，请手动选择文本");
    }
  }

  async function toggleFavorite(item) {
    if (!auth.isAuthenticated) {
      requestAuth({ featureLabel: "提示词收藏" });
      return;
    }
    if (!item?.id) return;
    const favorited = !item.favorited;
    try {
      await recordPromptEngagement(item.id, "favorite", favorited);
      const update = (entry) =>
        String(entry.id) === String(item.id)
          ? {
              ...entry,
              favorited,
              favoriteCount: Math.max(
                0,
                Number(entry.favoriteCount || 0) + (favorited ? 1 : -1),
              ),
            }
          : entry;
      setItems((current) => current.map(update));
      setPreview((current) => (current ? update(current) : current));
    } catch (error) {
      notificationService.error(error?.message || "收藏失败");
    }
  }

  async function usePrompt(item) {
    const prompt = String(item?.prompt || "").trim();
    if (!prompt) return;
    const taskType = item?.taskType || activeType || "t2i";
    stashPendingPrompt({ prompt, taskType });
    if (item?.id) {
      void recordPromptEngagement(item.id, "use", true).catch(() => null);
    }
    if (taskType === "t2i") {
      notificationService.success("已带到工作台");
    } else {
      try {
        await navigator.clipboard.writeText(prompt);
      } catch {
        // Navigation still succeeds when clipboard permission is unavailable.
      }
      notificationService.success("提示词已复制，请在工作台粘贴");
    }
    closePreview();
    navigate(studioRouteForTaskType(taskType));
  }

  function selectType(type) {
    if (type === activeType) return;
    setActiveType(type);
    setActiveCategory("all");
  }

  return (
    <main className="ch-page ch-page--prompts">
      <div className="ch-shell">
        <div className="ch-sticky-bar">
          <div className="ch-toolbar">
            <label className="ch-search">
              <i className="bi bi-search" aria-hidden="true" />
              <input
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                type="search"
                placeholder="搜索标题、提示词或标签"
              />
            </label>
          </div>
          <div className="ch-chips" aria-label="工作台">
            {PROMPT_TASK_TYPES.map((type) => (
              <button
                key={type.id}
                type="button"
                className={`ch-chip${activeType === type.id ? " is-active" : ""}`}
                onClick={() => selectType(type.id)}
              >
                {type.label}
              </button>
            ))}
          </div>
          <div className="ch-chips" aria-label="分类">
            {categoryMeta.map((category) => (
              <button
                key={category.id}
                type="button"
                className={`ch-chip${activeCategory === category.id ? " is-active" : ""}`}
                onClick={() => setActiveCategory(category.id)}
              >
                {category.label}
              </button>
            ))}
          </div>
        </div>

        <section className="ch-section">
          {loading && !filteredItems.length ? (
            <div className="ch-loading">正在加载提示词…</div>
          ) : !filteredItems.length ? (
            <div className="ch-empty">
              <strong>暂无提示词</strong>
              <span>换个分类试试，或稍后再来看官方更新</span>
            </div>
          ) : (
            <div
              ref={masonry.containerRef}
              className="ch-prompt-masonry"
              style={{ height: `${masonry.totalHeight}px` }}
            >
              {masonry.visibleItems.map((entry) => (
                <article
                  key={entry.key}
                  className="ch-card ch-prompt-masonry__item"
                  style={{
                    width: `${entry.width}px`,
                    height: `${entry.height}px`,
                    transform: `translate3d(${entry.left}px, ${entry.top}px, 0)`,
                  }}
                >
                  <button
                    type="button"
                    className="ch-card__media ch-prompt-card__media"
                    style={{ height: `${entry.mediaHeight}px` }}
                    onClick={() => openPreview(entry.item)}
                  >
                    {entry.cover ? (
                      <img
                        src={entry.cover}
                        alt={entry.item.title || "提示词"}
                        loading={
                          entry.index < Math.max(6, masonry.columnCount * 2)
                            ? "eager"
                            : "lazy"
                        }
                        fetchPriority={
                          entry.index < Math.max(4, masonry.columnCount)
                            ? "high"
                            : "low"
                        }
                        decoding="async"
                        width={Math.max(1, Math.round(entry.width))}
                        height={Math.max(1, entry.mediaHeight)}
                        onLoad={(event) =>
                          masonry.measureFromEvent(entry.key, event)
                        }
                      />
                    ) : (
                      <div className="ch-card__placeholder">
                        <i className="bi bi-quote" aria-hidden="true" />
                        {entry.item.title || "灵感"}
                      </div>
                    )}
                  </button>
                  <div className="ch-card__body">
                    <div className="ch-card__meta">
                      <span className="ch-pill">
                        {entry.item.category || activeTypeLabel}
                      </span>
                      {entry.item.useCount ? (
                        <span className="ch-pill">
                          <i className="bi bi-lightning-charge" aria-hidden="true" />
                          {entry.item.useCount}
                        </span>
                      ) : null}
                    </div>
                    <h3 className="ch-card__title">
                      {entry.item.title || entry.item.label || "未命名灵感"}
                    </h3>
                    <p className="ch-card__prompt" data-no-translate>
                      {entry.item.prompt}
                    </p>
                    <div className="ch-card__actions">
                      <button
                        type="button"
                        className="is-primary"
                        onClick={() => void usePrompt(entry.item)}
                      >
                        去做图
                      </button>
                      <button
                        type="button"
                        onClick={() => void copyPrompt(entry.item)}
                      >
                        复制
                      </button>
                      <button
                        type="button"
                        onClick={() => void toggleFavorite(entry.item)}
                      >
                        {entry.item.favorited ? "已收藏" : "收藏"}
                      </button>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          )}
          {hasMore || loadingMore ? (
            <div ref={loadSentinelRef} className="ch-more" aria-live="polite">
              {loadingMore ? <span className="ch-more__hint">加载中…</span> : null}
            </div>
          ) : null}
        </section>
      </div>

      {preview
        ? createPortal(
            <div
              className="ch-preview-layer"
              role="presentation"
              onMouseDown={(event) => {
                if (event.target === event.currentTarget) closePreview();
              }}
            >
              <button
                type="button"
                className="ch-preview__nav is-prev"
                disabled={!hasPreviewPrev}
                aria-label="上一条"
                onClick={() => showPreviewAt(previewIndex - 1)}
              >
                <i className="bi bi-chevron-left" aria-hidden="true" />
              </button>
              <button
                type="button"
                className="ch-preview__nav is-next"
                disabled={!hasPreviewNext}
                aria-label="下一条"
                onClick={() => showPreviewAt(previewIndex + 1)}
              >
                <i className="bi bi-chevron-right" aria-hidden="true" />
              </button>
              <div
                ref={previewPanelRef}
                className="ch-preview"
                role="dialog"
                aria-modal="true"
                aria-label="提示词详情"
              >
                <div className="ch-preview__media">
                  {preview.coverUrl || preview.imageUrl ? (
                    <img
                      src={preview.coverUrl || preview.imageUrl}
                      alt={preview.title || "提示词"}
                      loading="eager"
                      decoding="async"
                      fetchPriority="high"
                    />
                  ) : (
                    <div className="ch-preview__empty">暂无预览图</div>
                  )}
                </div>
                <aside className="ch-preview__body">
                  <div className="ch-preview__top">
                    <div className="ch-card__meta">
                      <span className="ch-pill">
                        {preview.category || activeTypeLabel}
                      </span>
                      {preview.useCount ? (
                        <span className="ch-pill">
                          <i className="bi bi-lightning-charge" aria-hidden="true" />
                          {preview.useCount}
                        </span>
                      ) : null}
                      {preview.favoriteCount ? (
                        <span className="ch-pill">
                          <i className="bi bi-heart" aria-hidden="true" />
                          {preview.favoriteCount}
                        </span>
                      ) : null}
                    </div>
                    <h2 className="ch-card__title" style={{ marginTop: 10 }}>
                      {preview.title || preview.label || "未命名灵感"}
                    </h2>
                  </div>
                  <div className="ch-preview__mid">
                    <p className="ch-preview__prompt" data-no-translate>
                      {preview.prompt || "暂无提示词"}
                    </p>
                  </div>
                  <div className="ch-preview__bottom">
                    <div className="ch-card__actions">
                      {preview.prompt ? (
                        <button
                          type="button"
                          className="is-primary"
                          onClick={() => void copyPrompt(preview)}
                        >
                          复制提示词
                        </button>
                      ) : null}
                      <button
                        type="button"
                        onClick={() => void usePrompt(preview)}
                      >
                        去做图
                      </button>
                      <button
                        type="button"
                        onClick={() => void toggleFavorite(preview)}
                      >
                        {preview.favorited ? "已收藏" : "收藏"}
                      </button>
                      <button type="button" onClick={closePreview}>
                        关闭
                      </button>
                    </div>
                  </div>
                </aside>
              </div>
            </div>,
            document.body,
          )
        : null}
    </main>
  );
}

// apps/web/src/views/PromptLibraryView.vue
<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import {
  listPromptCategories,
  listPromptLibrary,
  recordPromptEngagement,
} from '@/services/promptLibrary'
import notificationService from '@/services/notification'
import {
  PROMPT_TASK_TYPES,
  stashPendingPrompt,
  studioRouteForTaskType,
} from '@/features/creator-hub/studioTools'
import { useVirtualMasonryFeed } from '@/features/creator-hub/useVirtualMasonryFeed'
import { setBodyScrollLock } from '@/utils/bodyScrollLock'
import '@/features/creator-hub/creator-hub.css'

const router = useRouter()
const authStore = useAuthStore()

const PROMPT_PREVIEW_SCROLL_LOCK = 'prompt-library-preview'

const items = ref([])
const loading = ref(false)
const loadingMore = ref(false)
const page = ref(1)
const hasMore = ref(false)
const search = ref('')
const activeType = ref('t2i')
const activeCategory = ref('all')
const preview = ref(null)
const previewPanelRef = ref(null)
const loadSentinelRef = ref(null)
let requestId = 0
let loadObserver = null
let previewUnlockTimer = 0
let previewInertiaGuardCleanup = null

const PROMPT_SCOPE_CATEGORIES = [
  { id: 'all', label: '全部' },
  { id: 'today', label: '今日最新', scope: 'today' },
  { id: 'favorites', label: '我的收藏', scope: 'favorites' },
]
const promptCategories = ref([])
const categoryMeta = computed(() =>
  [...PROMPT_SCOPE_CATEGORIES, ...promptCategories.value].filter((item) => {
    if (item.scope === 'favorites' && !authStore.isAuthenticated) return false
    return true
  }),
)

async function loadPromptCategoryOptions() {
  try {
    const items = await listPromptCategories({ type: activeType.value })
    const scopeKeys = new Set(PROMPT_SCOPE_CATEGORIES.map((item) => item.id))
    promptCategories.value = items
      .filter((item) => !scopeKeys.has(item.key))
      .map((item) => ({ id: item.key, label: item.label }))
    if (!categoryMeta.value.some((item) => item.id === activeCategory.value)) {
      activeCategory.value = 'all'
    }
  } catch {
    promptCategories.value = []
  }
}

const activeTypeLabel = computed(
  () => PROMPT_TASK_TYPES.find((item) => item.id === activeType.value)?.label || '文生图',
)

const filteredItems = computed(() => {
  const q = search.value.trim().toLowerCase()
  if (!q) return items.value
  return items.value.filter((item) =>
    `${item.title || ''} ${item.prompt || ''} ${(item.tags || []).join(' ')}`
      .toLowerCase()
      .includes(q),
  )
})

const previewIndex = computed(() => {
  if (!preview.value) return -1
  const id = String(preview.value.id || '')
  if (id) return filteredItems.value.findIndex((item) => String(item.id) === id)
  return filteredItems.value.findIndex((item) => item === preview.value)
})

const hasPreviewPrev = computed(() => previewIndex.value > 0)
const hasPreviewNext = computed(
  () => previewIndex.value >= 0 && previewIndex.value < filteredItems.value.length - 1,
)

const masonryItems = computed(() =>
  filteredItems.value.map((item, index) => ({
    key: String(item.id || index),
    item,
    index,
    aspect:
      Number(item.coverWidth) > 0 && Number(item.coverHeight) > 0
        ? `${item.coverWidth} / ${item.coverHeight}`
        : '3 / 4',
    cover: item.coverUrl || item.imageUrl || '',
  })),
)

const {
  containerRef: masonryRef,
  visibleItems: visibleMasonryItems,
  columnCount,
  totalHeight: masonryHeight,
  measureFromEvent,
  scheduleViewportMeasure,
} = useVirtualMasonryFeed({
  items: masonryItems,
  fallbackAspect: 3 / 4,
  bodyHeight: 178,
  minColumnWidth: 260,
  maxColumns: 12,
  overscan: 960,
  getAspect: (entry) => entry.aspect,
})

function imageLoadingMode(index) {
  return index < Math.max(6, columnCount.value * 2) ? 'eager' : 'lazy'
}

function imageFetchPriority(index) {
  return index < Math.max(4, columnCount.value) ? 'high' : 'low'
}

function activeScope() {
  const hit = PROMPT_SCOPE_CATEGORIES.find((item) => item.id === activeCategory.value)
  return hit?.scope || ''
}

function categoryParam() {
  if (activeScope()) return ''
  return activeCategory.value === 'all' ? '' : activeCategory.value
}

function disconnectLoadObserver() {
  loadObserver?.disconnect()
  loadObserver = null
}

function setupLoadObserver() {
  disconnectLoadObserver()
  if (typeof IntersectionObserver === 'undefined') return
  const sentinel = loadSentinelRef.value
  if (!sentinel || !hasMore.value) return
  loadObserver = new IntersectionObserver(
    (entries) => {
      if (!entries.some((entry) => entry.isIntersecting)) return
      void loadPrompts({ reset: false })
    },
    { root: null, rootMargin: '1200px 0px', threshold: 0 },
  )
  loadObserver.observe(sentinel)
}

function stopPreviewInertiaGuard() {
  previewInertiaGuardCleanup?.()
  previewInertiaGuardCleanup = null
}

function startPreviewInertiaGuard(ms = 0, { allowPreviewScroll = false } = {}) {
  stopPreviewInertiaGuard()

  const shouldBlock = (event) => {
    if (!allowPreviewScroll) return true
    const scroller =
      event.target?.closest?.('.ch-preview__media') || event.target?.closest?.('.ch-preview__mid')
    if (!scroller) return true
    if (event.type === 'touchmove') return false

    const { scrollTop, scrollHeight, clientHeight } = scroller
    const delta = Number(event.deltaY) || 0
    if (scrollHeight <= clientHeight + 1) return true
    const atTop = scrollTop <= 0
    const atBottom = scrollTop + clientHeight >= scrollHeight - 1
    return (atTop && delta < 0) || (atBottom && delta > 0)
  }

  const onWheel = (event) => {
    if (shouldBlock(event)) event.preventDefault()
  }
  const onTouchMove = (event) => {
    if (shouldBlock(event)) event.preventDefault()
  }

  document.addEventListener('wheel', onWheel, { passive: false, capture: true })
  document.addEventListener('touchmove', onTouchMove, { passive: false, capture: true })

  const timer =
    ms > 0
      ? window.setTimeout(() => {
          document.removeEventListener('wheel', onWheel, { capture: true })
          document.removeEventListener('touchmove', onTouchMove, { capture: true })
          if (previewInertiaGuardCleanup) previewInertiaGuardCleanup = null
        }, ms)
      : 0

  previewInertiaGuardCleanup = () => {
    if (timer) window.clearTimeout(timer)
    document.removeEventListener('wheel', onWheel, { capture: true })
    document.removeEventListener('touchmove', onTouchMove, { capture: true })
  }
}

async function loadPrompts({ reset = true } = {}) {
  if (!reset && (loadingMore.value || loading.value || !hasMore.value)) return
  const id = reset ? ++requestId : requestId
  if (reset) {
    loading.value = true
    page.value = 1
    window.scrollTo({ top: 0, left: 0, behavior: 'auto' })
  } else {
    loadingMore.value = true
  }
  try {
    const nextPage = reset ? 1 : page.value + 1
    const response = await listPromptLibrary(activeType.value, {
      pageNumber: nextPage,
      pageSize: 24,
      category: categoryParam(),
      scope: activeScope(),
    })
    if (id !== requestId) return
    items.value = reset ? response.items || [] : [...items.value, ...(response.items || [])]
    page.value = nextPage
    hasMore.value = Boolean(response.hasMore)
  } catch (error) {
    if (reset) items.value = []
    notificationService.error(error?.message || '提示词读取失败')
  } finally {
    if (id === requestId) {
      loading.value = false
      loadingMore.value = false
      await nextTick()
      scheduleViewportMeasure()
      setupLoadObserver()
    }
  }
}

function setType(type) {
  if (activeType.value === type) return
  activeType.value = type
  activeCategory.value = 'all'
  void loadPromptCategoryOptions()
  window.scrollTo({ top: 0, left: 0, behavior: 'auto' })
}

function setCategory(id) {
  if (activeCategory.value === id) return
  activeCategory.value = id
  window.scrollTo({ top: 0, left: 0, behavior: 'auto' })
}

async function usePrompt(item) {
  const prompt = String(item?.prompt || '').trim()
  if (!prompt) return
  const taskType = item?.taskType || activeType.value || 't2i'
  stashPendingPrompt({ prompt, taskType })
  if (item?.id) {
    void recordPromptEngagement(item.id, 'use', true).catch(() => null)
  }
  if (taskType === 't2i') {
    notificationService.success('已带到工作台')
  } else {
    try {
      await navigator.clipboard.writeText(prompt)
    } catch {
      /* ignore */
    }
    notificationService.success('提示词已复制，请在工作台粘贴')
  }
  closePreview()
  await router.push(studioRouteForTaskType(taskType))
}

async function toggleFavorite(item) {
  if (!authStore.isAuthenticated) {
    notificationService.info('登录后可收藏提示词')
    return
  }
  if (!item?.id) return
  const next = !item.favorited
  try {
    await recordPromptEngagement(item.id, 'favorite', next)
    item.favorited = next
    item.favoriteCount = Math.max(0, Number(item.favoriteCount || 0) + (next ? 1 : -1))
  } catch (error) {
    notificationService.error(error?.message || '收藏失败')
  }
}

async function copyPrompt(item) {
  const prompt = String(item?.prompt || '').trim()
  if (!prompt) {
    notificationService.info('没有可复制的提示词')
    return
  }
  try {
    await navigator.clipboard.writeText(prompt)
    notificationService.success('提示词已复制')
  } catch {
    notificationService.error('复制失败，请手动选择文本')
  }
}

function openPreview(item) {
  if (previewUnlockTimer) {
    window.clearTimeout(previewUnlockTimer)
    previewUnlockTimer = 0
  }
  stopPreviewInertiaGuard()
  preview.value = item
  setBodyScrollLock(PROMPT_PREVIEW_SCROLL_LOCK, true, { freezeViewport: false })
  startPreviewInertiaGuard(0, { allowPreviewScroll: true })
  nextTick(() => {
    const media = previewPanelRef.value?.querySelector?.('.ch-preview__media')
    if (media) media.scrollTop = 0
  })
}

function showPreviewAt(index) {
  const item = filteredItems.value[index]
  if (!item) return
  preview.value = item
  nextTick(() => {
    const media = previewPanelRef.value?.querySelector?.('.ch-preview__media')
    const mid = previewPanelRef.value?.querySelector?.('.ch-preview__mid')
    if (media) media.scrollTop = 0
    if (mid) mid.scrollTop = 0
  })
}

function showPreviewPrev() {
  if (!hasPreviewPrev.value) return
  showPreviewAt(previewIndex.value - 1)
}

function showPreviewNext() {
  if (!hasPreviewNext.value) return
  showPreviewAt(previewIndex.value + 1)
}

function closePreview() {
  const root = previewPanelRef.value
  const media = root?.querySelector?.('.ch-preview__media')
  const mid = root?.querySelector?.('.ch-preview__mid')
  for (const el of [media, mid]) {
    if (!el) continue
    el.style.overflow = 'hidden'
    el.scrollTop = el.scrollTop
  }

  preview.value = null
  startPreviewInertiaGuard(450, { allowPreviewScroll: false })
  if (previewUnlockTimer) window.clearTimeout(previewUnlockTimer)
  previewUnlockTimer = window.setTimeout(() => {
    previewUnlockTimer = 0
    setBodyScrollLock(PROMPT_PREVIEW_SCROLL_LOCK, false)
  }, 50)
}

function onPreviewKeydown(event) {
  if (!preview.value) return
  if (event.key === 'Escape') {
    event.preventDefault()
    closePreview()
    return
  }
  if (event.key === 'ArrowLeft') {
    event.preventDefault()
    showPreviewPrev()
    return
  }
  if (event.key === 'ArrowRight') {
    event.preventDefault()
    showPreviewNext()
  }
}

watch([activeType, activeCategory], () => {
  void loadPrompts({ reset: true })
})

watch(preview, (value) => {
  if (typeof document === 'undefined') return
  if (value) document.addEventListener('keydown', onPreviewKeydown)
  else document.removeEventListener('keydown', onPreviewKeydown)
})

onMounted(() => {
  document.documentElement.classList.add('creator-hub-sticky-page')
  void loadPromptCategoryOptions()
  void loadPrompts({ reset: true })
})

onBeforeUnmount(() => {
  document.documentElement.classList.remove('creator-hub-sticky-page')
  document.removeEventListener('keydown', onPreviewKeydown)
  if (previewUnlockTimer) window.clearTimeout(previewUnlockTimer)
  stopPreviewInertiaGuard()
  setBodyScrollLock(PROMPT_PREVIEW_SCROLL_LOCK, false)
  disconnectLoadObserver()
})
</script>

<template>
  <main class="ch-page ch-page--prompts">
    <div class="ch-shell">
      <div class="ch-sticky-bar">
        <div class="ch-toolbar">
          <label class="ch-search">
            <i class="bi bi-search" aria-hidden="true"></i>
            <input v-model="search" type="search" placeholder="搜索标题、提示词或标签" />
          </label>
        </div>

        <div class="ch-chips" aria-label="工作台">
          <button
            v-for="type in PROMPT_TASK_TYPES"
            :key="type.id"
            type="button"
            class="ch-chip"
            :class="{ 'is-active': activeType === type.id }"
            @click="setType(type.id)"
          >
            {{ type.label }}
          </button>
        </div>

        <div class="ch-chips" aria-label="分类">
          <button
            v-for="cat in categoryMeta"
            :key="cat.id"
            type="button"
            class="ch-chip"
            :class="{ 'is-active': activeCategory === cat.id }"
            @click="setCategory(cat.id)"
          >
            {{ cat.label }}
          </button>
        </div>
      </div>

      <section class="ch-section">
        <div v-if="loading && !filteredItems.length" class="ch-loading">正在加载提示词…</div>

        <div v-else-if="!filteredItems.length" class="ch-empty">
          <strong>暂无提示词</strong>
          <span>换个分类试试，或稍后再来看官方更新</span>
        </div>

        <div
          v-else
          ref="masonryRef"
          class="ch-prompt-masonry"
          :style="{ height: `${masonryHeight}px` }"
        >
          <article
            v-for="entry in visibleMasonryItems"
            :key="entry.key"
            class="ch-card ch-prompt-masonry__item"
            :style="{
              width: `${entry.width}px`,
              height: `${entry.height}px`,
              transform: `translate3d(${entry.left}px, ${entry.top}px, 0)`,
            }"
          >
            <button
              type="button"
              class="ch-card__media ch-prompt-card__media"
              :style="{ height: `${entry.mediaHeight}px` }"
              @click="openPreview(entry.item)"
            >
              <img
                v-if="entry.cover"
                :src="entry.cover"
                :alt="entry.item.title || '提示词'"
                :loading="imageLoadingMode(entry.index)"
                :fetchpriority="imageFetchPriority(entry.index)"
                decoding="async"
                :width="Math.max(1, Math.round(entry.width))"
                :height="Math.max(1, entry.mediaHeight)"
                @load="measureFromEvent(entry.key, $event)"
              />
              <div v-else class="ch-card__placeholder">
                <i class="bi bi-quote" aria-hidden="true"></i>
                {{ entry.item.title || '灵感' }}
              </div>
            </button>
            <div class="ch-card__body">
              <div class="ch-card__meta">
                <span class="ch-pill">{{ entry.item.category || activeTypeLabel }}</span>
                <span v-if="entry.item.useCount" class="ch-pill">
                  <i class="bi bi-lightning-charge" aria-hidden="true"></i>
                  {{ entry.item.useCount }}
                </span>
              </div>
              <h3 class="ch-card__title">
                {{ entry.item.title || entry.item.label || '未命名灵感' }}
              </h3>
              <p class="ch-card__prompt" data-no-translate>{{ entry.item.prompt }}</p>
              <div class="ch-card__actions">
                <button type="button" class="is-primary" @click="usePrompt(entry.item)">
                  去做图
                </button>
                <button type="button" @click="copyPrompt(entry.item)">复制</button>
                <button type="button" @click="toggleFavorite(entry.item)">
                  {{ entry.item.favorited ? '已收藏' : '收藏' }}
                </button>
              </div>
            </div>
          </article>
        </div>

        <div v-if="hasMore || loadingMore" ref="loadSentinelRef" class="ch-more" aria-live="polite">
          <span v-if="loadingMore" class="ch-more__hint">加载中…</span>
        </div>
      </section>
    </div>

    <Teleport to="body">
      <div
        v-if="preview"
        class="ch-preview-layer"
        role="presentation"
        @mousedown.self="closePreview"
      >
        <button
          type="button"
          class="ch-preview__nav is-prev"
          :disabled="!hasPreviewPrev"
          aria-label="上一条"
          @click="showPreviewPrev"
        >
          <i class="bi bi-chevron-left" aria-hidden="true"></i>
        </button>
        <button
          type="button"
          class="ch-preview__nav is-next"
          :disabled="!hasPreviewNext"
          aria-label="下一条"
          @click="showPreviewNext"
        >
          <i class="bi bi-chevron-right" aria-hidden="true"></i>
        </button>

        <div
          ref="previewPanelRef"
          class="ch-preview"
          role="dialog"
          aria-modal="true"
          aria-label="提示词详情"
        >
          <div class="ch-preview__media">
            <img
              v-if="preview.coverUrl || preview.imageUrl"
              :src="preview.coverUrl || preview.imageUrl"
              :alt="preview.title || '提示词'"
              loading="eager"
              decoding="async"
              fetchpriority="high"
            />
            <div v-else class="ch-preview__empty">暂无预览图</div>
          </div>

          <aside class="ch-preview__body">
            <div class="ch-preview__top">
              <div class="ch-card__meta">
                <span class="ch-pill">{{ preview.category || activeTypeLabel }}</span>
                <span v-if="preview.useCount" class="ch-pill">
                  <i class="bi bi-lightning-charge" aria-hidden="true"></i>
                  {{ preview.useCount }}
                </span>
                <span v-if="preview.favoriteCount" class="ch-pill">
                  <i class="bi bi-heart" aria-hidden="true"></i>
                  {{ preview.favoriteCount }}
                </span>
              </div>
              <h2 class="ch-card__title" style="margin-top: 10px">
                {{ preview.title || preview.label || '未命名灵感' }}
              </h2>
            </div>

            <div class="ch-preview__mid">
              <p class="ch-preview__prompt" data-no-translate>
                {{ preview.prompt || '暂无提示词' }}
              </p>
            </div>

            <div class="ch-preview__bottom">
              <div class="ch-card__actions">
                <button
                  v-if="preview.prompt"
                  type="button"
                  class="is-primary"
                  @click="copyPrompt(preview)"
                >
                  复制提示词
                </button>
                <button type="button" @click="usePrompt(preview)">去做图</button>
                <button type="button" @click="toggleFavorite(preview)">
                  {{ preview.favorited ? '已收藏' : '收藏' }}
                </button>
                <button type="button" @click="closePreview">关闭</button>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </Teleport>
  </main>
</template>
